### PR TITLE
[WFLY-13031] EAP quickstart 'messaging-clustering-singleton' shows errors after import

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFLY-13031

### CODE REVIEW

**Comment by emmartins** [comment]
btw, I wonder if instead of removing the schema location there is an URL fix, similar to https://github.com/wildfly/quickstart/pull/365 ?

**Comment by RanabirChakraborty** [comment]
> this looks fine to me, yet would like someone else to assure the error is gone on Red Hat Code Ready Studio, @RanabirChakraborty can you do that please since you recently worked on similar issues?

Yeah sure @emmartins I'll help her :)

**Comment by parsharma** [comment]
> btw, I wonder if instead of removing the schema location there is an URL fix, similar to #365 ?

@emmartins  #365 is clone issue. Both issues are same. can we link it?

**Comment by parsharma** [comment]
Hi @emmartins, 
Please let me know do i link both the issues? Because i believed someone is also working on same issue.

**Pull request merged**
