### PR TITLE
[WFLY-18499] mp rest-client README rework

### PR DESCRIPTION
**Pull request by emmartins**
Issue: https://issues.redhat.com/browse/WFLY-18499
Followup of #780, reworks the README:
- Removes from scratch content that was outdated
- Adds 2 sections wrt accessing the app, and wrt the rest client

### CODE REVIEW

**Comment by jamezp** [comment]
@emmartins Do we want to remove the scratch content? I thought it was pretty good and when I walked through it it worked for me locally?

The other changes look fine.

**Comment by emmartins** [comment]
It didn’t work, and I believe this is what Yeray was reporting in the JIRA
too, cause it was missing some needed parts, but that actually wasn’t the
main reason for the rework, it was still targeting the old structure of
country server be country client, not matching your rework. Honestly
keeping up to date “from scratch” instructions have been a challenge to
maintain, and not just for this particular quickstart, but if you prefer to
keep it that way and fix the old content that’s fine. Personally I think
those are fine once, then become redundant, thus the “move” to the new app
dev doc.

**Comment by jamezp** [comment]
My only argument for keeping it would be this is supposed to be a client example, and it's kind of not a client example. The test is, but I'm not sure how relevant that is. The walk through just shows how to create the actual client which is kind of the point of the quickstart.

**Comment by emmartins** [comment]
@jamezp this was just my proposal for a quick fix, it would be good to have a fix for WFLY 31 beta, pls let me know if you want to propose something else

**Comment by emmartins** [comment]
sorry, wrong button, unintentional close :-)

**Comment by jamezp** [comment]
@emmartins It's up to you. I think they're good instructions, but if others tested and they didn't work I guess delete them. I'm not sure when I'd have time to update them TBH. I've got a lot on my plate right now.

**Comment by emmartins** [comment]
@jamezp ok I will merge this now, since it makes it read for xp5 qe, and whenever you have a chance and will feel free to rework such doc.

PS: we should end up moving all those "from scratch" content and integrate in the new guide anyway

**Pull request merged**
