### PR TITLE
[WFLY-16195] Upgrade security quickstarts

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFLY-16195
https://issues.redhat.com/browse/WFLY-16971

### CODE REVIEW

**Comment by soul2zimate** [comment]
Hi @fjuma , Since some configurations have been simplified and removed, does the community documentation require the same change? 

For example https://docs.wildfly.org/26.1/WildFly_Elytron_Security.html#set-up-and-configure-authentication-for-applications. (I know this is 26.1) AFAIU, some `simple-role-decoder` and `http-authentication-factory` additions are not necessary anymore.

**Comment by fjuma** [comment]
@soul2zimate Good question. Yes, if sections of the Docs add a `role-decoder` for Roles or configure an `http-authentication-factory` where a `security-domain` could be referenced instead, we should create WFLY issues to track this.

**Comment by kstekovi** [comment]
Hi @fjuma i went through the updated quickstarts and i notice there remaining almost empty beans.xml. I think they can be removed. Just microproprofile-jwt require it. because it change bean-discovery-mode from annotated to all. I think we should add annotation where it is required. What do you think?

**Comment by kstekovi** [comment]
The section `Access the Application` in `serverlet-security`, `helloworld-mutal-ssl`, 'helloworld-mutal-ssl-secured`, `security-domain-to-domain` have URL  `http://localhost:8080/{artifactId}/` but the variable `artifactId` is not defined in the README file. Could you please add it?

**Comment by kstekovi** [comment]
In the `ejb-security-context-propagation` in README is missing the variable `archiveType` with value `war`. In chapter `Build and Deploy the Quickstart` is `mvn clean install wildfly:deploy`. I think `package` is enough.

**Comment by kstekovi** [comment]
In `helloworld-mutal-ssl` and `helloworld-mutal-ssl-secured` is chapter `Import the Client Certificate into Your Browser`. The UI of both browser is updated so the the steps are little bit different.

**Comment by kstekovi** [comment]
In `helloworld-mutal-ssl-secured` is chaper `Remove the keystores and certificates created for this quickstart` and in step 1 `Open a terminal and navigate to the WildFly server configuration directory:` and command for a terminal is `$WILDFLY_HOME/bin/standalone.sh` instead `cd ./standalone/configuration`

**Comment by kstekovi** [comment]
In `security-domain-to-domain` in README are two chapter for restore configuration. `Restore the WildFly Standalone Server Configuration` and `Restore the Server Configuration`. Could be used just one of them?

**Comment by kstekovi** [comment]
In `microprofile-jwt` in chapter `Starting from Scratch` in section `Building and running the quickstart application in a bootable JAR`. There is a missing `<profiles></profiles>` section in pom.xml where the new bootable-jar profile should be added.

In profile is used property `version.server.bootable-jar` but this property is not defined.

**Comment by emmartins** [comment]
@kstekovi @fjuma please focus on changes only related with the JIRA, do not fix or improve anything else on the quickstart (feel free to open bug JIRAs for that tho)

**Comment by kstekovi** [comment]
In `helloworld-mutal-ssl` and `helloworld-mutal-ssl-secured` have updated secured content. So the automated test must be also updated.

**Comment by kstekovi** [comment]
In `serverlet-security` have warning message due to https://issues.redhat.com/browse/WFLY-16871

**Comment by fjuma** [comment]
> The section `Access the Application` in `serverlet-security`, `helloworld-mutal-ssl`, `helloworld-mutal-ssl-secured`, `security-domain-to-domain` have URL `http://localhost:8080/{artifactId}/` but the variable `artifactId` is not defined in the README file. Could you please add it?

The use of "{artifactId}" in the README.adoc files is common throughout all the quickstarts. The correct artifact ID gets populated when building the README.html files, as described here:
https://github.com/wildfly/quickstart/blob/main/README.adoc#4-prerequisites

**Comment by fjuma** [comment]
> In the `ejb-security-context-propagation` in README is missing the variable `archiveType` with value `war`. In chapter `Build and Deploy the Quickstart` is `mvn clean install wildfly:deploy`. I think `package` is enough.

The README has `archiveType` with value `jar`. This quickstart produces a `jar` so this looks fine.

For the change to the build command, since that's not related to changes made here, feel free to create a separate WFLY issue for that as @emmartins mentioned.

**Comment by fjuma** [comment]
> In `helloworld-mutal-ssl` and `helloworld-mutal-ssl-secured` is chapter `Import the Client Certificate into Your Browser` and `Remove the Client Certificate from Your Browser`. The UI of both browser is updated so the the steps are little bit different.


Good catch! I've fixed this.

**Comment by fjuma** [comment]
> In `helloworld-mutal-ssl-secured` is chaper `Remove the keystores and certificates created for this quickstart` and in step 1 `Open a terminal and navigate to the WildFly server configuration directory:` and command for a terminal is `$WILDFLY_HOME/bin/standalone.sh` instead `cd ./standalone/configuration`

Good catch, fixed!

**Comment by fjuma** [comment]
> In `security-domain-to-domain` in README are two chapter for restore configuration. `Restore the WildFly Standalone Server Configuration` and `Restore the Server Configuration`. Could be used just one of them?

Can you point me to the line where it's repeated? I'm not seeing it for some reason. Thanks.

**Comment by fjuma** [comment]
@kstekovi Just FYI, I've started going through the comments here. Will continue with what's left tomorrow. Thanks!

**Comment by kstekovi** [comment]
> > In `security-domain-to-domain` in README are two chapter for restore configuration. `Restore the WildFly Standalone Server Configuration` and `Restore the Server Configuration`. Could be used just one of them?
> 
> Can you point me to the line where it's repeated? I'm not seeing it for some reason. Thanks.

On [line 247](https://github.com/fjuma/quickstart-1/blob/c8f71f6c355c1127e3b69459ccce5b4b1ec150c4/security-domain-to-domain/README.adoc#L247) is include of shared documentation which describe Restore of the configuration.

And on [line 249](https://github.com/fjuma/quickstart-1/blob/c8f71f6c355c1127e3b69459ccce5b4b1ec150c4/security-domain-to-domain/README.adoc#L249) is new Heading about restoring the configuration and it continue with directs steps.

**Comment by fjuma** [comment]
> > > In `security-domain-to-domain` in README are two chapter for restore configuration. `Restore the WildFly Standalone Server Configuration` and `Restore the Server Configuration`. Could be used just one of them?
> > 
> > 
> > Can you point me to the line where it's repeated? I'm not seeing it for some reason. Thanks.
> 
> On [line 247](https://github.com/fjuma/quickstart-1/blob/c8f71f6c355c1127e3b69459ccce5b4b1ec150c4/security-domain-to-domain/README.adoc#L247) is include of shared documentation which describe Restore of the configuration.
> 
> And on [line 249](https://github.com/fjuma/quickstart-1/blob/c8f71f6c355c1127e3b69459ccce5b4b1ec150c4/security-domain-to-domain/README.adoc#L249) is new Heading about restoring the configuration and it continue with directs steps.

Thanks! I've removed the extra section.

**Comment by fjuma** [comment]
> In `microprofile-jwt` in chapter `Starting from Scratch` in section `Building and running the quickstart application in a bootable JAR`. There is a missing `<profiles></profiles>` section in pom.xml where the new bootable-jar profile should be added.
> 
> In profile is used property `version.server.bootable-jar` but this property is not defined.

For this one, it would be probably be good to create a separate WFLY issue to track this.

**Comment by fjuma** [comment]
> In `helloworld-mutal-ssl` and `helloworld-mutal-ssl-secured` have updated secured content. So the automated test must be also updated.

Where is the automated test?

**Comment by fjuma** [comment]
> `serverlet-security` have warning message due to https://issues.redhat.com/browse/WFLY-16871

Since there is an issue to track this, I think the presence of the warning message is ok.

**Comment by fjuma** [comment]
@kstekovi I think I've addressed all the comments here. Let me know if you have any questions or if I've missed anything. Thanks.

**Comment by kstekovi** [comment]
> > In `helloworld-mutal-ssl` and `helloworld-mutal-ssl-secured` have updated secured content. So the automated test must be also updated.
> 
> Where is the automated test?

It is part of QE tests so i will take care about this.

**Comment by kstekovi** [comment]
> @kstekovi I think I've addressed all the comments here. Let me know if you have any questions or if I've missed anything. Thanks.

Thank you very much. You addressed all.

**Pull request merged**
