### PR TITLE
[WFLY-15089] Add startup health checks to microprofile-health quickstart

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/WFLY-15089

### CODE REVIEW

**Comment by emmartins** [comment]
is this supposed to be just a README update?

**Comment by xstefank** [comment]
@emmartins yes, I decided to not add just another (same) health check with just changed qualifier. We need to revisit this as @jmesnil was mentioning on one F2F. Too much of the same example with just a really small change (changed qualifier) IMO.

**Comment by emmartins** [comment]
@xstefank so those new endpoints work without code changes?

**Comment by xstefank** [comment]
@emmartins yes, liveness, readiness no changes. Only /health will aggregate everything including the new startup checks. But there are no needed adjustments in the quickstart for that. We test startup normally in test suite so I don't see much value in adding a code example here.

**Pull request merged**
