### PR TITLE
[WFLY-19281] fixed name configuration attribute of wildfly-maven-plug…

### PR DESCRIPTION
**Pull request by istudens**
…in in provisioned-server profile

Issue: https://issues.redhat.com/browse/WFLY-18506

### CODE REVIEW

**Comment by emmartins** [comment]
this one I will need to put on hold till https://github.com/wildfly/quickstart/pull/895 is merged, due to plugin config changes

**Comment by emmartins** [comment]
please rebase

**Comment by istudens** [comment]
done

**Comment by emmartins** [comment]
thank you

**Pull request merged**
