### PR TITLE
Disable TLS in LRA quickstart

### PR DESCRIPTION
**Pull request by xstefank**
Issue: [WFLY-18901](https://issues.redhat.com/browse/WFLY-18901)

### CODE REVIEW

**Comment by xstefank** [comment]
@emmartins ready for review

**Comment by emmartins** [comment]
Kabir , I believe closing this one was a mistake. It was supposed to
reviewed by you too, I already approved it.

**Comment by xstefank** [comment]
@kabir correct, this shouldn't be closed. I can't reopen.

**Comment by kabir** [comment]
@emmartins reopened and CI has passed

**Comment by emmartins** [comment]
thank you @xstefank

**Pull request merged**
