### PR TITLE
WFLY-13473 Missing repositories in generated poms for MP QS in EAP

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/WFLY-13473

### CODE REVIEW

**Comment by rhusar** [comment]
@xstefank Needs a rebase, probably just a clean one but seems to have triggered a merge conflict.

**Comment by xstefank** [comment]
Fixed the conflict.

**Comment by emmartins** [comment]
@nziakova  can you please review?

**Comment by nziakova** [comment]
The change looks good, thank you. One note to possibly consider - it is a rather large amount of text copied to 7 (so far) readmes. Would it make sense to put it to shared-resources and just include it in these readmes? This way if similar QS is created in the future (with from-scratch instructions) the author could simply include prepared text without the risk of making copy-paste errors. Also could be better from maintenance point of view.

**Comment by nziakova** [comment]
Another option would be not including the prepared text directly in readme, just linking a doc which shows how to do that - could be better from readability point of view not to make the readme too long. I don't have strong opinion on which one would be better though.

**Comment by emmartins** [comment]
@nziakova @xstefank I believe a link jump would make it harder to follow, I agree using a shared-docs section  is an improvement tho.

**Comment by xstefank** [comment]
done in the added file (option 1).

**Comment by nziakova** [comment]
@emmartins I think you are right and having to follow a link would really make it harder to follow. Just wanted to show another option because the instructions are getting long. However, it's a step-by-step guide so it should not be an issue for users that chose that option (there's still the short path with complete example).

**Comment by emmartins** [comment]
@darranl @rhusar @pferraro since this will be applied to your QS too, anything against it?

**Comment by rhusar** [comment]
@emmartins Looks good assuming Martin knows what he is doing :-)

**Pull request merged**
