### PR TITLE
WFLY-13458 Issues in readme for microprofile-health QS

### PR DESCRIPTION
**Pull request by xstefank**
https://issues.redhat.com/browse/WFLY-13458

### CODE REVIEW

**Comment by xstefank** [comment]
@nziakova can you take a look, please?

**Comment by nziakova** [comment]
@xstefank Thank you for the fixes. It looks better now, although I can only tell from which shared resources have been added. What I am still missing is (3) from JIRA - "The checks array is empty as we have not specified any health check procedure yet so let's define some." is not correct because it comes after the complete example deployment - please correct me if I am wrong.

**Comment by xstefank** [comment]
@nziakova I've included Undeploy section before the Creating project from scratch section. So the user following section by section should undeploy the full quickstart before proceeding with create from scratch. That should solve the issue.

However, in the Solution section I want to point people to either full quickstart (only deploy) **OR** Create project from scratch. It didn't occur to me that someone will do both :) Can this be communicated better?

**Comment by xstefank** [comment]
And you can generate the README.html with `mvn clean package -Pdocs` if you would like to check the full expanded sections.

**Comment by nziakova** [comment]
I think it is pointed out fine that user should follow complete example OR step-by-step one. Still the sentence about empty checks is between deploying and undeploying the complete example, so if someone follows the complete example instructions, they will get different output than documented.

**Comment by xstefank** [comment]
@nziakova thank you. I see what I missed now. I just removed the sentence as it's not that important.

**Comment by xstefank** [comment]
@emmartins @nziakova I believe everything is fixed now and this can be merged.

**Comment by emmartins** [comment]
looks good to me, if @nziakova has nothing against I will merge it shortly

**Comment by nziakova** [comment]
Nothing from me, feel free to merge.

**Pull request merged**
