### PR TITLE
Verify and re-enable tasks-jsf quickstart

### PR DESCRIPTION
**Pull request by scottmarlow**
https://issues.redhat.com/browse/WFLY-17533

- Updated datasource URL to instruct H2 to ignore `USER` keyword in SQL statements.
- Enabled tasks-jsf quickstart

I suspect that further application changes may be needed as we can create users but no further UI is displayed other than:
1.  Open http://localhost:8080/tasks-jsf/index.jsf and enter "scott" for user name, press login button.
2. Browser only shows `Tasks - Authentication`. 
3. Server console shows `14:42:30,946 INFO  [jakarta.enterprise.resource.webcontainer.faces.renderkit] (default task-1) WARNING: FacesMessage(s) have been enqueued, but may not have been displayed.
sourceId=null[severity=(INFO 0), summary=(User successfully created), detail=(User successfully created)]`

@emmartins @jasondlee is there a known fix for why the tasks-jsf quickstart doesn't show anything interesting in the browser after a user is created?  I assume there should be a menu or something shown but the browser doesn't show anything that can be clicked on.

### CODE REVIEW

**Comment by emmartins** [comment]
@scottmarlow I have not tried in a while, but I guess it should work similar to pre jakarta ee 10 wfly releases, I will try to check it out later in case you are not able to do it

**Comment by scottmarlow** [comment]
The tasks-jsf quickstart doc mentions there should be the following in the user interface:
```
SF is used to present the user two views.

authentication form: This provides the simple login

task view: This view contains the task list, a task detail, and a task addition form. The task view uses AJAX.
```

I'll take another look.

**Comment by scottmarlow** [comment]
It seems like the application is not yet working as there is no UI displayed for adding `tasks` and no Faces error messages appear in the console that I see.

**Comment by scottmarlow** [comment]
@jasondlee is there a Faces TRACE logging setting that might show why the `tasks-jsf` quick start is not displaying the ability to add tasks?  

The browser UI does allow the user to login but after they login, they don't see any options to proceed further.

**Comment by emmartins** [comment]
@jasondlee can you please give a hand on solving this, I suspect it needs JSF changes like you did some time ago to EAP 8 Beta quickstarts

**Comment by jasondlee** [comment]
> @jasondlee can you please give a hand on solving this, I suspect it needs JSF changes like you did some time ago to EAP 8 Beta quickstarts

I'm looking into this now, but I don't have much experience with navigation-rules, so I'll have to do some digging. `AuthController.authenticate()` seems to be working as expecting, but the system is not navigating as it should, based on the config.

**Comment by jasondlee** [comment]
> @jasondlee is there a Faces TRACE logging setting that might show why the `tasks-jsf` quick start is not displaying the ability to add tasks?

The easiest way is to add `<h:messages/>` to the view, which I did and I get "User successfully created", which is not super helpful. :)

**Comment by jasondlee** [comment]
@emmartins @scottmarlow,

Got it. Two issues:

1. The first is the xmlns is incorrect, so the parser was ignoring the rules in the config file (I would verify the value for all of the JSF quickstarts)
2. The from-action didn't quite match the action in the view.

Diff:
```

diff --git a/tasks-jsf/src/main/webapp/WEB-INF/faces-config.xml b/tasks-jsf/src/main/webapp/WEB-INF/faces-config.xml
index e337d9e40..aa16e2a18 100644
--- a/tasks-jsf/src/main/webapp/WEB-INF/faces-config.xml
+++ b/tasks-jsf/src/main/webapp/WEB-INF/faces-config.xml
@@ -15,19 +15,19 @@
     See the License for the specific language governing permissions and
     limitations under the License.
 -->
-<faces-config xmlns="http://xmlns.jcp.org/xml/ns/javaee"
-              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
-              xsi:schemaLocation="
-                  https://jakarta.ee/xml/ns/jakartaee
-                  https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_4_0.xsd"
-              version="4.0">
+<faces-config
+        xmlns="https://jakarta.ee/xml/ns/jakartaee"
+        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+        xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
+                https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_4_0.xsd"
+        version="4.0">
     <navigation-rule>
         <from-view-id>/index.xhtml</from-view-id>
         <navigation-case>
-            <from-action>#{authController.authenticate(username)}</from-action>
+            <from-action>#{authController.authenticate}</from-action>
             <if>#{authController.logged}</if>
             <to-view-id>/tasks.xhtml</to-view-id>
-            <redirect />
+            <redirect/>
         </navigation-case>
     </navigation-rule>
 
@@ -37,7 +37,7 @@
             <from-action>#{authController.logout}</from-action>
             <if>#{!authController.logged}</if>
             <to-view-id>/index.xhtml</to-view-id>
-            <redirect />
+            <redirect/>
         </navigation-case>
     </navigation-rule>
```

**Comment by scottmarlow** [comment]
Either @jasondlee will push his commit with the above change to github if he still has it.  If Jason doesn't have it, I'll (or anyone else can) copy/paste the change from the above comment with details and push that to github to be brought into this pr.

**Comment by emmartins** [comment]
hi @scottmarlow, please do the proposed changes, and verify it now works as expected.

PS: please do a main branch rebase too to solve the current conflicts

**Comment by scottmarlow** [comment]
Updated faces-config.xml and now see failure:
```
14:45:36,704 WARN  [org.wildfly.extension.microprofile.opentracing] (MSC service thread 1-3) WFLYTRACEXT0012: No Jaeger endpoint or sender-binding configured. Installing a no-op sender
14:45:36,705 INFO  [io.jaegertracing.internal.JaegerTracer] (MSC service thread 1-3) No shutdown hook registered: Please call close() manually on application shutdown.
14:45:36,705 INFO  [org.wildfly.microprofile.opentracing.smallrye] (MSC service thread 1-3) WFLYTRAC0001: Tracer initialized: JaegerTracer(version=Java-1.6.0, serviceName=tasks-jsf.war, reporter=RemoteReporter(sender=NoopSender(), closeEnqueueTimeout=1000), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=localhost.localdomain, jaeger.version=Java-1.6.0, ip=127.0.0.1}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)
14:45:36,719 INFO  [org.jipijapa] (MSC service thread 1-7) JIPIORMV6020260: Second level cache enabled for tasks-jsf.war#primary
14:45:36,748 INFO  [org.jboss.as.jpa] (ServerService Thread Pool -- 80) WFLYJPA0010: Starting Persistence Unit (phase 2 of 2) Service 'tasks-jsf.war#primary'
14:45:36,750 INFO  [SQL dialect] (ServerService Thread Pool -- 80) HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
14:45:36,753 INFO  [org.hibernate.envers.boot.internal.EnversServiceImpl] (ServerService Thread Pool -- 80) Envers integration enabled? : true
14:45:36,963 INFO  [jakarta.enterprise.resource.webcontainer.faces.config] (ServerService Thread Pool -- 80) Initializing Mojarra 4.0.0.SP01 for context '/tasks-jsf'
14:45:36,987 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 80) WFLYUT0021: Registered web context: '/tasks-jsf' for server 'default-server'
14:45:37,029 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0016: Replaced deployment "tasks-jsf.war" with deployment "tasks-jsf.war"
14:45:37,031 INFO  [org.jboss.as.repository] (management-handler-thread - 1) WFLYDR0002: Content removed from location /home/smarlow/work/wildfly/dist/target/wildfly-28.0.0.Beta1-SNAPSHOT/standalone/data/content/73/d92e129cbddb969f2ef9c1ab2c37d9f0a2653c/content
14:45:44,604 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /tasks-jsf/tasks.jsf: jakarta.servlet.ServletException: viewId:/tasks.jsf - View /tasks.jsf could not be restored.
        at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:709)
        at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.smallrye.opentracing-contrib//io.smallrye.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:69)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
        at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
        at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
        at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
        at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at org.wildfly.security.elytron-web.undertow-server-servlet@3.0.0.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
        at io.undertow.core@2.3.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
        at io.undertow.core@2.3.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
        at org.jboss.xnio@3.8.8.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jakarta.faces.application.ViewExpiredException: viewId:/tasks.jsf - View /tasks.jsf could not be restored.
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:164)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:95)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
        at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
        ... 49 more

14:46:07,100 SEVERE [jakarta.enterprise.resource.webcontainer.faces.context] (default task-1) jakarta.faces.component.UpdateModelException: jakarta.el.PropertyNotWritableException: /tasks.xhtml @76,87 value="#{taskController.taskTitle}": The class 'org.jboss.as.quickstarts.tasksJsf.TaskController' does not have a writable property 'taskTitle'.: jakarta.faces.component.UpdateModelException: jakarta.el.PropertyNotWritableException: /tasks.xhtml @76,87 value="#{taskController.taskTitle}": The class 'org.jboss.as.quickstarts.tasksJsf.TaskController' does not have a writable property 'taskTitle'.
        at jakarta.faces.api//jakarta.faces.component.UIInput.updateModel(UIInput.java:721)
        at jakarta.faces.api//jakarta.faces.component.UIInput.processUpdates(UIInput.java:622)
        at jakarta.faces.api//jakarta.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:938)
        at jakarta.faces.api//jakarta.faces.component.UIForm.processUpdates(UIForm.java:253)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:589)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:158)
        at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1266)
        at jakarta.faces.api//jakarta.faces.component.UIForm.visitTree(UIForm.java:344)
        at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
        at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
        at jakarta.faces.api//jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:392)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:250)
        at jakarta.faces.api//jakarta.faces.component.UIViewRoot.processUpdates(UIViewRoot.java:1303)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.UpdateModelValuesPhase.execute(UpdateModelValuesPhase.java:50)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
        at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
        at jakarta.faces.api//jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.smallrye.opentracing-contrib//io.smallrye.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:69)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.lambda$handleRequest$1(ElytronRunAsHandler.java:68)
        at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.FlexibleIdentityAssociation.runAsFunctionEx(FlexibleIdentityAssociation.java:103)
        at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAsFunctionEx(Scoped.java:161)
        at org.wildfly.security.elytron-base@2.0.0.Final//org.wildfly.security.auth.server.Scoped.runAs(Scoped.java:73)
        at org.wildfly.security.elytron-web.undertow-server@3.0.0.Final//org.wildfly.elytron.web.undertow.server.ElytronRunAsHandler.handleRequest(ElytronRunAsHandler.java:67)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.core@2.3.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at org.wildfly.security.elytron-web.undertow-server-servlet@3.0.0.Final//org.wildfly.elytron.web.undertow.server.servlet.CleanUpHandler.handleRequest(CleanUpHandler.java:38)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
        at io.undertow.core@2.3.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1429)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
        at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
        at io.undertow.core@2.3.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:391)
        at io.undertow.core@2.3.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at org.jboss.xnio@3.8.8.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jakarta.el.PropertyNotWritableException: /tasks.xhtml @76,87 value="#{taskController.taskTitle}": The class 'org.jboss.as.quickstarts.tasksJsf.TaskController' does not have a writable property 'taskTitle'.
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:99)
        at jakarta.faces.api//jakarta.faces.component.UIInput.updateModel(UIInput.java:696)
        ... 66 more
Caused by: jakarta.el.PropertyNotWritableException: The class 'org.jboss.as.quickstarts.tasksJsf.TaskController' does not have a writable property 'taskTitle'.
        at jakarta.el.api@4.0.0.Final//jakarta.el.BeanELResolver.setValue(BeanELResolver.java:261)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.el.DemuxCompositeELResolver._setValue(DemuxCompositeELResolver.java:199)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.el.DemuxCompositeELResolver.setValue(DemuxCompositeELResolver.java:222)
        at org.glassfish.expressly@5.0.0//org.glassfish.expressly.parser.AstValue.setValue(AstValue.java:197)
        at org.glassfish.expressly@5.0.0//org.glassfish.expressly.ValueExpressionImpl.setValue(ValueExpressionImpl.java:184)
        at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.module.web.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
        at com.sun.jsf-impl@4.0.0.SP01//com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:95)
        ... 67 more
```

**Comment by jasondlee** [comment]
I'm working on fixing these issues in my local branch....

**Comment by emmartins** [comment]
superseeded by #646

**Pull request closed without merging**
