### PR TITLE
[WFLY-18027] moved package org.wildfly.quickstarts.todos to org.jboss…

### PR DESCRIPTION
**Pull request by istudens**
….as.quickstarts.todos

Issue: https://issues.redhat.com/browse/WFLY-18027

### CODE REVIEW

**Comment by darranl** [comment]
Does this really need to change?  Across WildFly we already have many many packages already using org.wildfly

**Comment by jamezp** [comment]
+1 I don't see a need for this at all. TBH if any of them are `org.jboss.*` they should be moved to `org.willdfly.*`. Not that we need to make that change, but that feels like the direction to go, not the opposite.

**Comment by istudens** [comment]
This change is marked as critical for 8.0.0.Beta-CR1, see https://issues.redhat.com/browse/JBEAP-24264 .

**Comment by darranl** [comment]
I think that is an issue that needs to be triaged further.  I am not sure it is valid but that needs to be discussed to come to a conclusion.

**Comment by emmartins** [comment]
closing as agreed we wont do this change

**Pull request closed without merging**
