### PR TITLE
WFLY-15406 ha-singleton-service quickstart fails to build

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFLY-15406

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
Since you are removing one of the messages, the quick start text (README.adoc) no longer corresponds with the code.

**Comment by pferraro** [comment]
@rhusar Which message did I remove?

**Comment by pferraro** [comment]
I didn't remove any messages, but I did change the content (slightly).  I'll adjust the README.

**Comment by pferraro** [comment]
@rhusar README should be synced now.

**Review by rhusar — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
