### PR TITLE
[WFLY-17678] [WFLY-18942] Micrometer QS on OpenShift

### PR DESCRIPTION
**Pull request by emmartins**
Clean up YAML
Add instructions for install otel collector on OS
OpenShift CI setup

Issues: [WFLY-15842](https://issues.redhat.com/browse/WFLY-15842) , [WFLY-17678](https://issues.redhat.com/browse/WFLY-17678) ,

### CODE REVIEW

**Comment by emmartins** [comment]
Superseeds https://github.com/wildfly/quickstart/pull/869

**Review by kabir — APPROVED** [review]
Acking that the OpenShift tests ran and passed

**Comment by kstekovi** [comment]
Ack. The OpenShift steps works as is described. LGTM.

**Review by kstekovi — APPROVED** [review]

**Comment by emmartins** [comment]
thank you @kstekovi @jasondlee @kabir

**Pull request merged**
