### PR TITLE
[WFLY-14201][WFLY-14398] MP Config 2.0 changes

### PR DESCRIPTION
**Pull request by kabir**
https://issues.redhat.com/browse/WFLY-14201
https://issues.redhat.com/browse/WFLY-14398

### CODE REVIEW

**Comment by jmesnil** [comment]
@kabir That's not related to your PR (LGTM) but I'd really like to change the `/` endpoint for this app.

That's the one I use for my demo and I hate having to deploy it on OpenShift, open it and get a super helpful message:

> MicroProfile Config quickstart deployed successfully. You can find the available operations in the included README file.

Really? I deploy your app and you tell me to RTFM? ;)

Could you change it to print out a list of links to these operations? or a just a link to `/config/value` would be more helpful than that message :)

**Review by jmesnil — APPROVED** [review]

**Comment by xstefank** [comment]
@jmesnil haha, that was a QE requirement. But I agree, something more helpful would be better :)

**Review by xstefank — APPROVED** [review]

**Review by rhusar — APPROVED** [review]

**Comment by emmartins** [comment]
@jmesnil @kabir IMHO such root page changes (and docs too I guess) should be done in a separated JIRA tho, and be applied to all dev branches

**Comment by rhusar** [comment]
@emmartins Don't we require quickstarts to be deployed on the context named after the quickstart? Anything deploying to root sounds like a bug to me.

**Comment by rhusar** [comment]
+1 Links to what the app does would definitely make these apps more user friendly and yes, ideally across the board - at least for the MP ones.

**Comment by emmartins** [comment]
@rhusar I meant root of quickstart, which may be the server root (openshift, bootable jar) or not (bare-metal) :-)

**Pull request merged**
