### PR TITLE
[WFLY-17332] Fix narayana dependency, the correct artifact is again j…

### PR DESCRIPTION
**Pull request by emmartins**
…bossxts
Issue: https://issues.redhat.com/browse/WFLY-17332

### CODE REVIEW

**Comment by emmartins** [comment]
Please note that BUILD DEFAULT tests are expected to fail, this change are a followup of the changes on BOMs by wildfly/boms#123

**Comment by marcosgopen** [comment]
@emmartins Could you tell me when the version.server.bom will be updated (to the version that contains https://github.com/wildfly/boms/pull/123 ) so that the wsat-simple, wsba* quickstarts start working again?

**Comment by emmartins** [comment]
@marcosgopen WFLY 28 Beta

**Comment by marcosgopen** [comment]
Thanks @emmartins !

**Pull request merged**
