### PR TITLE
JBEAP-15613: Replace deprecated org.hibernate.validator.constraints w…

### PR DESCRIPTION
**Pull request by sgilda**
https://issues.jboss.org/browse/JBEAP-15613

### CODE REVIEW

**Comment by sgilda** [comment]
I need an experienced Java engineer to review these code changes for accuracy as I have not written code in quite a while.

**Comment by emmartins** [comment]
I will have a look at it tomorrow.

**Comment by sgilda** [comment]
thanks @ctomc !

**Comment by emmartins** [comment]
@sgilda can you please revert the hibernate4 changes, no deprecation on that one

**Comment by sgilda** [comment]
@emmartins : The hibernate4 changes are reverted.

**Pull request merged**
