### PR TITLE
WFLY-13035:added <DOCTYPE xml>

### PR DESCRIPTION
**Pull request by sudeshnas93**
Issue: https://issues.redhat.com/browse/WFLY-13035

### CODE REVIEW

**Comment by emmartins** [comment]
@sudeshnas93 the JIRA refers 4 XML files yet this PR only fixes 2, is that correct?
PS: minor PR/commit format issue, please use "[WFLY-XXXXX] commit msg"

**Comment by sudeshnas93** [comment]
@emmartins Changed rest 2 files as well. Let me know if there needs to be any other change.

**Comment by emmartins** [comment]
@sudeshnas93 now looking at all 4, what's the idea of the DOCTYPE tag, turn off IDE validation?

**Comment by sudeshnas93** [comment]
> @sudeshnas93 now looking at all 4, what's the idea of the DOCTYPE tag, turn off IDE validation?

what I know DOCTYPEs are a key component of compliant web pages. Markup and CSS won’t validate without them but I don't think IDE validation has any relation with it.

**Pull request closed without merging**
