### PR TITLE
WFLY-11835 Expand ha-singleton-deployment and -service quickstarts to…

### PR DESCRIPTION
**Pull request by rhusar**
… demonstrate using CLI to determine primary provider

Jira
https://issues.jboss.org/browse/WFLY-11835

### CODE REVIEW

**Comment by emmartins** [comment]
retest this please

**Comment by rhusar** [comment]
retest this please

**Comment by rhusar** [comment]
@emmartins What's the status of this?

**Comment by rhusar** [comment]
@emmartins The CI fails consistently for everything. Is there any plan on fixing the CI runs?

**Comment by emmartins** [comment]
@rhusar sorry, all fixed now, was due to parent 35 enforcing https maven repos

**Pull request merged**
