### PR TITLE
JBEAP-12048: Fix formatting issues in ha-singleton-service README file

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by sgilda** [comment]
@rhusar : The other quickstarts that run multiple servers have used the underscore throughout the 6.x and 7.0 releases. We need to be consistent in this one.

**Comment by sgilda** [comment]
Closing this and creating a new PR.

**Comment by rhusar** [comment]
In that case, the others can be fixes to use the sane choice (dash) as opposed to unnecessary underscores.

**Comment by sgilda** [comment]
@rhusar : QE requested underscores in the JIRA. Can you make your comments and arguments there?

**Comment by rhusar** [comment]
Looking at this again, once its rendered the ${jboss.home.name} are replaced by EAP_HOME_7 or something like that, so using the underscores here is fine.

**Comment by sgilda** [comment]
@rhusar : Yes. I'm sorry that I wasn't more clear. Most of the quickstarts have only one server and use _EAP_HOME_. When there is more than one server, it becomes _EAP_HOME_1_, _EAP_HOME_2_, etc.

**Pull request closed without merging**
